import type { Vector2D } from './types';
export const DISTRICTS = [
  {
    id: 'market',
    name: 'Phố chợ',
    icon: '🧺',
    color: '#e7bf80',
    description: 'Hẻm ngang dọc, quầy hàng và những chuyến xe nhộn nhịp.',
  },
  {
    id: 'downtown',
    name: 'Trung tâm',
    icon: '🏛️',
    color: '#b9c8df',
    description: 'Đường rộng, văn phòng và khách đang vội.',
  },
  {
    id: 'old-town',
    name: 'Chợ Lớn',
    icon: '🏮',
    color: '#e3ad94',
    description: 'Dãy nhà dài, lối tắt nhỏ và đèn lồng.',
  },
  {
    id: 'riverside',
    name: 'Ven sông',
    icon: '🌿',
    color: '#9acbbb',
    description: 'Khoảng trời thoáng, hàng cây và gió bên bến nước.',
  },
] as const;
export function districtAt(p: Vector2D) {
  return DISTRICTS[p.y < 2000 ? (p.x < 2000 ? 0 : 1) : p.x < 2000 ? 2 : 3];
}
export const LANDMARKS = [
  {
    id: 'ben-thanh',
    name: 'Chợ Bến Thành',
    x: 1250,
    y: 1350,
    icon: '🧺',
    district: 'market',
    story: 'Ghé chợ, nghe tiếng rao, rồi đón một chuyến xe mới.',
  },
  {
    id: 'tan-dinh',
    name: 'Chợ Tân Định',
    x: 850,
    y: 950,
    icon: '🌸',
    district: 'market',
    story: 'Màu hồng rực rỡ và những quầy hàng thân quen.',
  },
  {
    id: 'cho-nho',
    name: 'Chợ nhỏ đầu hẻm',
    x: 1650,
    y: 550,
    icon: '🥬',
    district: 'market',
    story: 'Bó rau, túi bánh và câu chào buổi sáng.',
  },
  {
    id: 'duc-ba',
    name: 'Nhà thờ Đức Bà',
    x: 2450,
    y: 950,
    icon: '⛪',
    district: 'downtown',
    story: 'Một điểm hẹn quen thuộc giữa trung tâm thành phố.',
  },
  {
    id: 'post-office',
    name: 'Bưu điện thành phố',
    x: 2850,
    y: 1350,
    icon: '✉️',
    district: 'downtown',
    story: 'Những lá thư nhỏ bắt đầu hành trình xa.',
  },
  {
    id: 'opera',
    name: 'Nhà hát thành phố',
    x: 3250,
    y: 1750,
    icon: '🎭',
    district: 'downtown',
    story: 'Ánh đèn sân khấu chờ khách đến đúng giờ.',
  },
  {
    id: 'binh-tay',
    name: 'Chợ Bình Tây',
    x: 850,
    y: 2950,
    icon: '🏮',
    district: 'old-town',
    story: 'Mỗi con hẻm quanh chợ đều có một câu chuyện.',
  },
  {
    id: 'thien-hau',
    name: 'Miếu Thiên Hậu',
    x: 1250,
    y: 3350,
    icon: '🐉',
    district: 'old-town',
    story: 'Dừng chân trước mái ngói và sắc đỏ ấm áp.',
  },
  {
    id: 'lan-ong',
    name: 'Phố thuốc Hải Thượng',
    x: 450,
    y: 2550,
    icon: '🌱',
    district: 'old-town',
    story: 'Mùi thảo mộc thoảng theo một chuyến xe chậm rãi.',
  },
  {
    id: 'thu-thiem',
    name: 'Bến Thủ Thiêm',
    x: 2850,
    y: 2550,
    icon: '🌉',
    district: 'riverside',
    story: 'Ngắm đường chân trời từ bờ sông lộng gió.',
  },
  {
    id: 'bach-dang',
    name: 'Bến Bạch Đằng',
    x: 2450,
    y: 2950,
    icon: '⛵',
    district: 'riverside',
    story: 'Một cuộc hẹn nhẹ nhàng bên bến nước.',
  },
  {
    id: 'riverside-park',
    name: 'Công viên ven sông',
    x: 3250,
    y: 3350,
    icon: '🌳',
    district: 'riverside',
    story: 'Hàng cây rợp bóng cho chuyến xe cuối chiều.',
  },
] as const;
